# Generated by Django 4.2.21 on 2025-05-28 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evento', '0013_alter_evento_email'),
        ('inscricao', '0002_alter_inscricao_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evento', to='evento.evento', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participante', to=settings.AUTH_USER_MODEL, verbose_name='Participante'),
        ),
    ]
