# Generated by Django 4.2.21 on 2025-06-04 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0016_evento_hora_inicio'),
        ('inscricao', '0005_alter_inscricao_participante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='evento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='evento', to='evento.evento', verbose_name='Evento'),
        ),
    ]
