# Generated by Django 4.2.22 on 2025-06-09 08:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0017_evento_grupo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inscricao', '0006_alter_inscricao_evento'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscricao',
            unique_together={('evento', 'participante')},
        ),
    ]
