# Generated by Django 4.2.22 on 2025-06-09 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0017_evento_grupo'),
        ('inscricao', '0007_alter_inscricao_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evento', to='evento.evento', verbose_name='Evento'),
        ),
    ]
