# Generated by Django 4.2.22 on 2025-06-11 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0008_alter_inscricao_evento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscricao',
            options={'ordering': ['-is_active', 'evento', 'participante__nome'], 'verbose_name': 'inscrição', 'verbose_name_plural': 'inscrições'},
        ),
    ]
