# Generated by Django 4.2.21 on 2025-05-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0010_evento_lotacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='data_divulgacao_trabalhos_aprovados',
        ),
    ]
