# Generated by Django 4.2.21 on 2025-05-27 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0011_remove_evento_data_divulgacao_trabalhos_aprovados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='arquivo_modelo',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='coordenador_suplente',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='data_limite_reenvio_trabalhos_corrigidos',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='modelo_artigo',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='publicado',
        ),
    ]
