# Generated by Django 4.2.21 on 2025-05-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0012_remove_evento_arquivo_modelo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='email',
            field=models.EmailField(blank=True, help_text='Campo opcional, caso o evento seja de submissão de trabalhos.', max_length=100, null=True, verbose_name='Email oficial da organização'),
        ),
    ]
