# Generated by Django 4.2.21 on 2025-05-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0013_alter_evento_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='codigo_frequencia',
            field=models.CharField(blank=True, help_text='Código que será utilizado para solicitar a frequência do evento. Deve ser informado ao participante no final do evento.', max_length=20, null=True, verbose_name='Código de frequência'),
        ),
        migrations.AddField(
            model_name='evento',
            name='frequencia_liberada',
            field=models.BooleanField(default=False, help_text='Se liberada, o evento permite que os participantes solicitem a frequência', verbose_name='Libera a frequência'),
        ),
    ]
