# Generated by Django 4.2.21 on 2025-05-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0014_evento_codigo_frequencia_evento_frequencia_liberada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='codigo_frequencia',
            field=models.CharField(help_text='Código que será utilizado para solicitar a frequência do evento. Deve ser informado ao participante no final do evento.', max_length=20, null=True, verbose_name='Código de frequência'),
        ),
    ]
