# Generated by Django 4.2.21 on 2025-06-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0015_alter_evento_codigo_frequencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='hora_inicio',
            field=models.TimeField(help_text='Use hh:mm', null=True, verbose_name='Hora de início do evento *'),
        ),
    ]
