# Generated by Django 4.2.21 on 2025-06-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0016_evento_hora_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='grupo',
            field=models.CharField(help_text='* Campo obrigatório', max_length=150, null=True, verbose_name='Departamento ou Setor ou Grupo responsável pelo evento *'),
        ),
    ]
