# Generated by Django 4.2.22 on 2025-06-11 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0017_evento_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='lotacao',
            field=models.DecimalField(decimal_places=0, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='Lotação máxima do local do evento '),
        ),
    ]
