# Generated by Django 4.2.22 on 2025-06-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0018_alter_evento_lotacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='nome',
            field=models.CharField(db_index=True, help_text='* Campo obrigatório', max_length=150, verbose_name='Nome do evento *'),
        ),
        migrations.AlterUniqueTogether(
            name='evento',
            unique_together={('nome', 'data_inicio')},
        ),
    ]
