# Generated by Django 4.2.21 on 2025-05-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Se ativo, o aviso aparece na home dos participantes', verbose_name='Selecione para publicar na home dos usuários o aviso'),
        ),
    ]
