# Generated by Django 4.2.22 on 2025-06-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviso', '0002_alter_aviso_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='titulo',
            field=models.CharField(help_text='* Campos obrigatórios', max_length=100, unique=True, verbose_name='Título do aviso *'),
        ),
    ]
