# Generated by Django 5.1.7 on 2025-05-21 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscricao', '0002_alter_inscricao_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_frequencia', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inscricao.inscricao', unique=True, verbose_name='Inscrição do evento *')),
            ],
            options={
                'verbose_name': 'frequência',
                'verbose_name_plural': 'frequências',
                'ordering': ['inscricao'],
            },
        ),
    ]
