# Generated by Django 5.1.7 on 2025-05-21 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequencia', '0001_initial'),
        ('inscricao', '0002_alter_inscricao_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia',
            name='inscricao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscricao', to='inscricao.inscricao', unique=True, verbose_name='Inscrição do evento *'),
        ),
    ]
