# Generated by Django 4.2.21 on 2025-05-30 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0005_alter_inscricao_participante'),
        ('frequencia', '0002_alter_frequencia_inscricao'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='frequencia',
            unique_together={('inscricao',)},
        ),
    ]
