# Generated by Django 4.2.21 on 2025-05-30 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0005_alter_inscricao_participante'),
        ('frequencia', '0003_alter_frequencia_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia',
            name='inscricao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscricao', to='inscricao.inscricao', verbose_name='Inscrição do evento *'),
        ),
    ]
