# Generated by Django 4.2.21 on 2025-06-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequencia', '0004_alter_frequencia_inscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='codigo_frequencia',
            field=models.CharField(blank=True, help_text='Código que será utilizado para solicitar a frequência do evento. Deve ser informado ao participante no final do evento.', max_length=20, null=True, verbose_name='Código de frequência'),
        ),
    ]
