# Generated by Django 4.2.22 on 2025-06-11 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frequencia', '0007_alter_frequencia_inscricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frequencia',
            options={'ordering': ['inscricao__participante__nome'], 'verbose_name': 'frequência', 'verbose_name_plural': 'frequências'},
        ),
    ]
