# Generated by Django 4.2.22 on 2025-08-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atestado_manual', '0007_alter_atestadomanual_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='atestadomanual',
            name='papel',
            field=models.CharField(choices=[('PARTICIPANTE', 'Participante'), ('MINISTRANTE', 'Ministrante')], default='PARTICIPANTE', help_text='* Campo obrigatório. Se não tiver certeza, escolha Participante.', max_length=20, verbose_name='Papel na atividade *'),
        ),
    ]
