# Generated by Django 4.2.22 on 2025-06-11 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['-is_active', '-tipo', 'nome'], 'verbose_name': 'usuário', 'verbose_name_plural': 'usuários'},
        ),
    ]
